name: project-demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run maven build
        run: mvn clean install
      - name: Setup localstack
        run: |
          pip install localstack awscli-local[ver1] terraform-local
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStatck startup..."
          localstack wait -t 30
          echo "Startup complete"
      - name: Run terraform
        run: |
          cd localstack/terraform
          tflocal init
          tflocal plan
          tflocal apply --auto-approve
      - name: Copy file to s3 to trigger lambda
        run: |
          pwd
          echo "List SNS topic subscription..."
          awslocal sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:000000000000:test-topic-01
          echo "Get lambda configuration"
          awslocal lambda get-function-configuration --function-name Sqs_Event_Lambda 
          echo "Get lambda event-source-mapping"
          awslocal lambda list-event-source-mappings --function-name Sqs_Event_Lambda
          cd localstack/terraform
          awslocal s3api put-object --bucket test-bucket-01 --key main.tf --body main.tf
          echo "Wait for 150 seconds..."
          sleep 150
          echo "Execute \"awslocal s3 ls s3://test-bucket-01 --human-readable\""
          awslocal s3 ls s3://test-bucket-01 --human-readable
          echo "Wait for another 150 seconds..."
          sleep 150
          echo "Execute \"awslocal sqs get-queue-attributes\""
          awslocal sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/test-queue-01 --attribute-names All 
          echo "Wait for another 150 seconds..."
          sleep 150
          echo "Execute \"awslocal sqs get-queue-attributes\""
          awslocal sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/test-queue-02 --attribute-names All 
          echo "Wait for another 150 seconds..."
          sleep 150
          echo "Execute \"awslocal s3 ls s3://test-bucket-02 --human-readable\""
          awslocal s3 ls s3://test-bucket-02 --human-readable
