name: project-demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run maven build
        run: mvn clean install
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Setup localstack
        run: |
          pip install localstack awscli-local[ver1] terraform-local
          docker pull localstack/localstack
          LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=120 HOSTNAME_EXTERNAL=awslocal localstack start -d
          echo "Waiting for LocalStatck startup..."
          localstack wait -t 30
          echo "Startup complete"
      - name: Run terraform
        run: |
          cd localstack/terraform
          tflocal init
          tflocal plan
          tflocal apply --auto-approve
      - name: Check localstack
        run: |
          ping -c 10 localhost.localstack.cloud
      - name: Test AWS Lambda Functions
        run: |
          pwd
          cd localstack/terraform
          echo "Copy file to s3 bucket..."
          awslocal s3api put-object --bucket test-bucket-01 --key main.tf --body main.tf
          sleep 30
          echo "Check whether file uploaded to the s3 bucket or not"
          awslocal s3api head-object --bucket test-bucket-01 --key main.tf || NOT_EXIST=true
          if [ $NOT_EXIST ]; then
              echo "main.tf was not uploaded to test-bucket-01"
              exit 1
          fi
          echo "Wait 120 seconds for sqs event lambda process"
          sleep 120
          awslocal logs filter-log-events --log-group-name "/aws/lambda/Sqs_Event_Lambda" --query 'events[*].message'
          awslocal s3api head-object --bucket test-bucket-02 --key main.tf || NOT_EXIST=true
          if [ $NOT_EXIST ]; then
              echo "Test failed. File main.tf was not copied to test-bucket-02"
              exit 1
          else
              echo "Test success. File main.tf found in test-bucket-02"
          fi