name: project-demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run maven build
        run: mvn clean install
      - name: Setup localstack
        run: |
          pip install localstack awscli-local[ver1] terraform-local
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStatck startup..."
          localstack wait -t 30
          echo "Startup complete"
      - name: Run terraform
        run: |
          cd localstack/terraform
          tflocal init
          tflocal plan
          tflocal apply --auto-approve
      - name: Copy file to s3
        run: |
          cd localstack/terraform
          awslocal s3api put-object --bucket test-bucket-01 --key main.tf
          awslocal s3 ls s3://test-bucket-01 --human-readable
          awslocal s3 ls s3://test-bucket-02 --human-readable